/**
 * @(#)arrayExample1.java
 *
 *
 * @author 
 * @version 1.00 2015/9/10
 */
import java.util.Random;

public class arrayExample1 {
        
    
    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) { //begin main
    // ***** declare constants *****
    
    	final int MAX = 10;			// maximum number of randoms allowed
    
    // ***** declare variables *****
    
        Random r = new Random();		// create new random object
        int[] list = new int[MAX];		// declare and allocate a new array
        
        int rnd;				// random number generated by r
        int n;					// counter for loop
        
    // ***** banners *****
    
    // ***** processing *****
    /* generate a series of random numbers
     * use a while loop to create and count numbers.
     */
     
     // **** load the array ***
     n = 0;				// prim conrol variable
     
     while(n < MAX){ // begin while\
     
     	// ***  random number ***
     	
     	rnd = r.nextInt(128);				// generate a random number between 0 and 127
     	list[n] = rnd;						// assign the random number to an array element
     	//System.out.println("random number " + n + ". = " + rnd);
     	
     	// *** update control
     	
     	n++;									// update control variable
     }  // end while
    
    // ***** processing the array *****
    
    // ** print array **
    
    for(int i = 0; i < n; i++){
    	System.out.println("random number " + (i + 1) + ". = " + list[i]);
    } // end for int i (print array)
     
	// ***** closing message *****
	   
        System.out.println("end of processing?");
    } // end main
} // end public class
